In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Activation
from keras.layers import Flatten
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.utils import to_categorical
from keras.datasets import mnist

2024-12-16 15:19:21.433219: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-16 15:19:21.435796: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-12-16 15:19:21.445446: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1734373161.462161    4412 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734373161.467376    4412 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-16 15:19:21.485200: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

In [2]:
(train_samples, train_labels), (test_samples, test_labels) = mnist.load_data()

In [3]:
train_samples = train_samples.reshape(train_samples.shape[0], 28, 28, 1)
test_samples = test_samples.reshape(test_samples.shape[0], 28, 28, 1)
train_samples = train_samples.astype('float32')
test_samples = test_samples.astype('float32')
train_samples = train_samples/255
test_samples = test_samples/255

In [4]:
c_train_labels = to_categorical(train_labels, 10)
c_test_labels = to_categorical(test_labels, 10)

In [5]:
convnet = Sequential()
convnet.add(Convolution2D(32, 4, 4, activation='relu', input_shape=(28,28,1)))
convnet.add(MaxPooling2D(pool_size=(2,2), padding='same'))
convnet.add(Convolution2D(32, 3, 3, activation='relu'))
convnet.add(MaxPooling2D(pool_size=(2,2), padding='same'))
convnet.add(Dropout(0.3))
convnet.add(Flatten())
convnet.add(Dense(10, activation='softmax'))

/home/sukuna963/anaconda3/envs/venv/lib/python3.12/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
W0000 00:00:1734373171.797303    4412 gpu_device.cc:2344] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [6]:
convnet.compile(loss='mean_squared_error', optimizer='sgd', metrics=['accuracy'])

In [7]:
convnet.fit(train_samples, c_train_labels, batch_size=32, epochs=20, verbose=1)

Epoch 1/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.1060 - loss: 0.0903
Epoch 2/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.1299 - loss: 0.0900
Epoch 3/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.1597 - loss: 0.0898
Epoch 4/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.1769 - loss: 0.0897
Epoch 5/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.1858 - loss: 0.0895
Epoch 6/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.1948 - loss: 0.0893
Epoch 7/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.2003 - loss: 0.0891
Epoch 8/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.2052 - loss: 0.0889
Epoch 9/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.2151 - loss: 0.0885
Epoch 10/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.2186 - loss: 0.0881
Epoch 11/20
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.2230 - loss: 0.0876
Epoch 12/20
1875/1875 ━━━━━━━━

In [8]:
metrics = convnet.evaluate(test_samples, c_test_labels, verbose=1)
print()
print("%s: %.2f%%" % (convnet.metrics_names[1], metrics[1]*100))
predictions = convnet.predict(test_samples)
print(predictions)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.4182 - loss: 0.0723

compile_metrics: 43.21%
313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step
[[0.05841501 0.02947382 0.0769033  ... 0.34354433 0.07020346 0.1597978 ]
 [0.0738232  0.23568664 0.10487669 ... 0.03329877 0.11359464 0.04947847]
 [0.02682912 0.68417907 0.0157177  ... 0.02675335 0.03320013 0.02716607]
 ...
 [0.04800801 0.13183947 0.07432872 ... 0.26863143 0.09190789 0.12881061]
 [0.0676555  0.12934017 0.050208   ... 0.2457305  0.05601139 0.1410337 ]
 [0.27779332 0.01715337 0.17680307 ... 0.05499944 0.10254742 0.05000152]]
